version: "3.7"
services:
    database:
        image: postgres
        restart: always
        env_file:
            - .env
        expose:
            - "${POSTGRES_PORT}"
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data:z
    server:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - database
        networks:
            - default
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
volumes:
    data:

